on: [workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: arefdsg/gha-setup-swift@main
        with:
          branch: swift-5.5-release
          tag: 5.5-RELEASE

      - uses: actions/checkout@v2
      - run: swift build
      - run: swift test
